os:
  - linux
  - windows
matrix:
  allow_failures:
    - os: windows
language: node_js
node_js:
  - 12
compiler:
  - gcc
after_success: npm run-script build
before_deploy:
    - cd "./dist/release/"
    - zip -r papyrusjs-$TRAVIS_OS_NAME_$TRAVIS_TAG-$TRAVIS_BUILD_NUMBER.zip ./
deploy:
    branches:
        only:
            - master
    provider: releases
    overwrite: true
    tags: true
    file: papyrusjs-$TRAVIS_OS_NAME_$TRAVIS_TAG-$TRAVIS_BUILD_NUMBER.zip
    on:
        repo: clarkx86/papyrusjs
        tags: true
    skip_cleanup: true
